author: "Vadim Tsushko <vadimtsushko@gmail.com>"
description: "Dart wrapper for ag-grid"
name: "ag_grid"
version: "0.3.0"
dependencies: 
  browser: ">=0.10.0 <0.11.0"
#  dart_to_js_script_rewriter: "^1.0.1"
  dart_to_js_script_rewriter: "^1.0.2"
  func: ">=1.0.0"
  js: "^0.6.0"
  js_util: "any"
dev_dependencies:
  test: "^0.12.24+6"
environment:
  sdk: ">=1.0.0 <2.0.0"
transformers: 
  - "dart_to_js_script_rewriter"
