name: 'ag_grid'
version: 0.1.1
description: Dart wrapper for ag-grid
author: Vadim Tsushko <vadimtsushko@gmail.com>

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^0.1.0'
  js: ^0.6.0
  func: ^0.1.0
transformers:
- dart_to_js_script_rewriter